pipeline {
    agent any
    environment{
        app_version = 'version1'
    }
    stages{

        stage('Stage 0: Build'){
            steps{
                sh "docker-compose build"
  
            }

            }
        stage ("Pull") {
            steps{
                sh "bash jenkins/scripts/clone_repo.sh"
            }
        }    
        stage ("Terraform"){
                    steps {
                        sh "bash jenkins/scripts/terraform_build.sh"
                        
                    }
                }
        stage ("Deploy"){
            steps {
                sh "echo deploy"
                sh "sh jenkins/scripts/kubernetes_run.sh"
            }
        }